# Generated by Django 5.0 on 2024-01-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yemekler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='category',
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ManyToManyField(blank=True, to='yemekler.category'),
        ),
    ]
