# Generated by Django 4.1.7 on 2024-01-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yemekler', '0002_remove_food_category_food_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='Katagori',
            field=models.ManyToManyField(blank=True, to='yemekler.kategori'),
        ),
    ]
