# Generated by Django 4.1.7 on 2024-01-06 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yemekler', '0005_rename_katagori_program_kategori'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='Kategori',
        ),
        migrations.DeleteModel(
            name='Kategori',
        ),
    ]
