# Generated by Django 4.1.7 on 2024-01-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yemekler', '0008_remove_program_katego_delete_prokategori'),
    ]

    operations = [
        migrations.CreateModel(
            name='pkategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='pkategori',
            field=models.ManyToManyField(blank=True, to='yemekler.pkategori'),
        ),
    ]
