# Generated by Django 4.1.7 on 2024-01-09 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yemekler', '0011_yorum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yorum',
            name='post',
        ),
    ]
